### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by tonisnark**
In #763 you said "This project is placed in the public domain." Let's make it official with a permissive free-software license. Either this one or the newer [BSD Zero Clause](https://choosealicense.com/licenses/0bsd/) ought to do the trick.

### CODE REVIEW

**Comment by snarfed** [comment]
thanks for the contribution!

just out of curiosity, do you have a use case for this? eg using the codebase as open source inside a company that requires `LICENSE` files, surveying projects with a tool that analyzes them, getting the license to show up in the github UI, etc?

(i'm not strictly opposed to adding a `LICENSE` file...but fwiw, in a legal sense, the declaration is already "official." 😄)

**Comment by tonisnark** [comment]
You'd be surprised how many people won't touch software without a license. And currently, you don't have one.

**Comment by tonisnark** [comment]
You'd be surprised [how many people](https://blog.codinghorror.com/pick-a-license-any-license/) won't touch software without a license. And, with all due respect, you don't have one. My use case is FOSS exploration for a lightweight, scalable Webmention solution for my website.

**Comment by tonisnark** [comment]
You'd be surprised [how many people](https://blog.codinghorror.com/pick-a-license-any-license/) won't touch software without a license. And, with all due respect, you don't have one. My use case is FOSS exploration for a lightweight, scalable Webmention solution.

**Comment by tonisnark** [comment]
Exploration complete. I see you're heavily reliant on Google Cloud Storage and that's a no fly zone for my purposes. Please consider adding a license to your software—and not just your docs.

**Comment by snarfed** [comment]
bridgy itself doesn't actually use google cloud storage, but it does run on google cloud, specifically app engine, and i do have (partial) datastore backups on cloud storage.

sorry to hear that's a problem for you. hope you find what you're looking for!

**Pull request closed without merging**
