### PR TITLE
publish: allow users to sign up for Instagram/publish and publish likes

### PR DESCRIPTION
**Pull request by kylewm**
- preview and create likes. preview uses Instagram OEmbed code 
- because bridgy is not approved, give a sensible error on comment
  creation

(I did this as a pull request since it was quite wide-spread and would feel 
better having another pair of eyes on it first)

Addresses #326

### CODE REVIEW

**Comment by snarfed** [comment]
ok! modulo just a couple nits, and hopefully dropping `__getattr__`, this lgtm. :+1:

**Comment by snarfed** [comment]
oh, and we'll want to update the about page too! that can be a separate commit though.

**Comment by kylewm** [comment]
ok, I did some local testing of bridgy and a-u instagram, and it looks good to me. the /about changes will be ... a little delicate (not subtle), i'll take a crack at them.

**Comment by snarfed** [comment]
thanks for the manual testing!

**Pull request merged**
