### PR TITLE
appending old inReplyTos

### PR DESCRIPTION
**Pull request by stedn**
calls new function in granary https://github.com/snarfed/granary/pull/204 to append inReplyTos from the old object to the new, if applicable.

### CODE REVIEW

**Comment by snarfed** [comment]
pretty simple. 😁 do you know how you'll test this?

**Comment by stedn** [comment]
i was hoping you could tell me :smiley:

**Comment by snarfed** [comment]
heh yeah, i'd usually add a unit test. sorry, feels like a lot for a one line change, i know! probably just as much effort to try to set up a manual test, though, and the unit test will obviously last a lot longer. 😎

**Comment by stedn** [comment]
I found the place for the unit test.  sorry that took me a while to get around to. this still relies on the change in granary for the test to pass though https://github.com/snarfed/granary/pull/204
but it worked locally

**Comment by snarfed** [comment]
nice! test is almost there, you may just be missing a `util.trim_nulls()` or something similar to fix this failure: https://app.circleci.com/pipelines/github/snarfed/bridgy/37/workflows/580b71ed-aec9-44d2-bc14-036c54f63ebd/jobs/1129/parallel-runs/0/steps/0-105

**Comment by snarfed** [comment]
woo! deploying this now.

**Comment by stedn** [comment]
sweet! if nothing lights on fire today, i'll send a message out tonight and see if people can test the many toots at once problem from before.

**Comment by snarfed** [comment]
i polled a busy mastodon account just now and it worked fine. feel free to spread the word!

**Pull request merged**
