### PR TITLE
posse-post discovery for multiple rel=feeds

### LINKED ISSUE #423: PPD: crawl all rel=feed links, not just the first
this has a been a known, low priority limitation for a while. @kartikprabhu [hit it recently](http://indiewebcamp.com/irc/2015-07-14#t1436887460416).

@kylewm, do you remember if there was a reason we did this, other than just load?

### PR DESCRIPTION
**Pull request by kylewm**
e.g. support for rel=feed for notes and one for articles. this fixes #423

### CODE REVIEW

**Comment by snarfed** [comment]
yay, thanks for doing this! and for including the test! looks great, feel free to merge whenever.

btw, i was thinking about redirects...if multiple rel-feeds redirect to the same url, i think this will reprocess that url each time...but that's a very weird unlikely case, and i don't think we'd duplicate `SyndicatedPost`s since we de-dupe them by final post permalink, so i don't care.

**Comment by snarfed** [comment]
oh, also, feel free to deploy after you merge! the last api key i added was 5/2 (superfeedr), and i'm guessing you've deployed since then, so you should have them all. (six silos + disqus + superfeedr.) the other big new change is virtualenv, but if you have the tests and dev_appserver running, you should be fine.

**Comment by kylewm** [comment]
interesting thought. we could certainly call 

```python
feed_url, _, feed_type_ok = util.get_webmention_target(feed_url)
```

every time instead of only when type is not given.

**Comment by snarfed** [comment]
we could! i don't have a strong opinion, especially since i expect we'll see this so rarely, if at all. up to you!

**Comment by snarfed** [comment]
(we may see roughly it as often as a site lies about a feed's type in the `<link>` elem. :P)

**Comment by kylewm** [comment]
cool thank you, I will try to deploy tonight!

**Comment by snarfed** [comment]
sgtm! i'm offline from ~4pm today through ~2pm tomorrow, just fyi if you want backup. totally ok if you deploy tonight though. i figure worst case is i forgot a silo api key or two, and those silo(s) stop polling for a day or so, i don't care, esp since it's over a friday night!

here's the full list i have, btw:
```
disqus_access_token
disqus_api_key
disqus_api_secret
facebook_app_id
facebook_app_id_local.bak
facebook_app_secret
facebook_app_secret_local
facebook_test_user_access_token
google_client_id
google_client_secret
instagram_client_id
instagram_client_id_local
instagram_client_secret
instagram_client_secret_local
superfeedr_token
tumblr_app_key
tumblr_app_secret
twitter_access_token_key
twitter_access_token_secret
twitter_app_key
twitter_app_secret
wordpress.com_client_id
wordpress.com_client_id_local
wordpress.com_client_secret
wordpress.com_client_secret_local
```

**Comment by kylewm** [comment]
huh, I do not have `disqus_access_token`, is there a Bridgy user for posting Disqus comments now?

**Comment by snarfed** [comment]
yup! that's actually how it's been from the beginning, iirc, since it doesn't let you set a name and picture per comment. https://disqus.com/by/bridgyapp/

i'll send the token!

**Pull request merged**
