### PR TITLE
OPD: don't refetch h-feed if we already fetched it earlier in the poll

### PR DESCRIPTION
**Pull request by snarfed**
related to #597

### CODE REVIEW

**Comment by snarfed** [comment]
@kylewm this seems like another source of multiple OPDs/h-feed fetches during a single poll. does it make sense? or am i conflating normal OPD and refetch and they're really different enough that we may want both sometimes?

**Comment by snarfed** [comment]
on a related note, i should probably move this `last_hfeed_fetch` check inside `refetch()` so that it's checked and set in the same place, for readability.

**Comment by kylewm** [comment]
I don't think we want this -- refetch is pretty different from the normal discover in that it removes all the blanks and refetches the individual permalinks. We don't want to short-circuit that behavior even though we ran the regular fetch earlier in this same round.

**Comment by kylewm** [comment]
In fact, it seems wrong to me that we are tracking `last_fetch_feed` in both places. I think it should just be tracking the time between *refetches* is more than 2 hours or whatever. There's no reason to enforce a delay between a normal fetch and refetch.

**Comment by kylewm** [comment]
It looks like that was changed in https://github.com/snarfed/bridgy/commit/21e37d75fd262be7dbb84fdd67ba756f4ef0a57e for #538,

**Comment by snarfed** [comment]
aha, good point, thanks! i'd forgotten the difference. so we should probably ideally call it `last_hfeed_refetch`?

the rename probably isn't a priority, but i'd be fine with ignoring it during normal OPD fetch. along with some comments to remind me not to regress it in the future. :P

**Comment by kylewm** [comment]
> aha, good point, thanks! i'd forgotten the difference. so we should probably ideally call it last_hfeed_refetch?

Seriously. That was a bad name choice on my part! You just coded the behavior implied by the name :P

**Comment by snarfed** [comment]
i'm convinced, i'll close this. thanks for reviewing. we could also file an issue to rename it to `last_hfeed_refetch`...but meh!

**Pull request closed without merging**
